#include "tunnel/wgconfig.h"

#include "crypto/crypto.h"

#include <cstdlib>
#include <stdexcept>

namespace scshr::tunnel {

std::string render_windows_conf(const WindowsTunnelConfig& c) {
    if (!valid_wg_key(c.private_key)) throw std::invalid_argument("tunnel config: invalid local private key");
    if (!valid_wg_key(c.peer_public_key)) throw std::invalid_argument("tunnel config: invalid peer public key");
    if (!valid_tunnel_ip(c.win_ip)) throw std::invalid_argument("tunnel config: invalid local tunnel address");
    if (!valid_endpoint_host(c.endpoint_host)) throw std::invalid_argument("tunnel config: invalid endpoint host");
    if (c.endpoint_port == 0) throw std::invalid_argument("tunnel config: invalid endpoint port");
    std::string why;
    if (!route_allowed(c.peer_ip + "/32", &why)) throw std::invalid_argument("tunnel config: peer route rejected: " + why);
    if (c.peer_ip == c.win_ip) throw std::invalid_argument("tunnel config: local and peer tunnel IPs must differ");

    // Deliberately minimal: no DNS (the system resolver is never touched), no Table/MTU override,
    // and an AllowedIPs of exactly one host — so WireGuard installs one /32 route and nothing else.
    std::string s;
    s += "# Generated by scshr init - do not edit by hand.\n";
    s += "# scshr application tunnel: one Windows peer <-> one macOS peer, no default route, no DNS.\n";
    s += "[Interface]\n";
    s += "PrivateKey = " + c.private_key + "\n";
    s += "Address = " + c.win_ip + "/32\n";
    s += "\n";
    s += "[Peer]\n";
    s += "PublicKey = " + c.peer_public_key + "\n";
    s += "AllowedIPs = " + c.peer_ip + "/32\n";
    s += "Endpoint = " + c.endpoint_host + ":" + std::to_string(c.endpoint_port) + "\n";
    s += "PersistentKeepalive = " + std::to_string(kPersistentKeepalive) + "\n";
    return s;
}

std::string describe_windows_conf(const WindowsTunnelConfig& c) {
    return "address=" + c.win_ip + "/32 peer=" + key_fingerprint(c.peer_public_key) +
           " allowed-ips=" + c.peer_ip + "/32 endpoint=" + c.endpoint_host + ":" + std::to_string(c.endpoint_port) +
           " keepalive=" + std::to_string(kPersistentKeepalive) + "s";
}

std::string key_fingerprint(const std::string& public_key_b64) {
    std::string raw;
    if (!wg_key_bytes(public_key_b64, raw)) return "<invalid>";
    const auto d = crypto::sha256(ByteView(reinterpret_cast<const uint8_t*>(raw.data()), raw.size()));
    return hex(ByteView(d.data(), 8));
}

}  // namespace scshr::tunnel
