package main

import "testing"

const (
	privKey = "AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dw="
	peerKey = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8="
)

const paired = `# Generated by scshr-macos-tunnel.sh - do not edit by hand.
[Interface]
PrivateKey = ` + privKey + `
Address = 10.77.77.1/32
ListenPort = 51820

[Peer]
PublicKey = ` + peerKey + `
AllowedIPs = 10.77.77.2/32
`

const unpaired = `[Interface]
PrivateKey = ` + privKey + `
Address = 10.77.77.1/32
ListenPort = 51820
`

func TestParseAccepts(t *testing.T) {
	c, err := parseConf(paired)
	if err != nil {
		t.Fatalf("paired config rejected: %v", err)
	}
	if c.Address.String() != "10.77.77.1" || c.ListenPort != 51820 {
		t.Fatalf("wrong interface: %+v", c)
	}
	if !c.HasPeer || c.PeerAllowedIP.String() != "10.77.77.2" || c.PeerPublicKey != peerKey {
		t.Fatalf("wrong peer: %+v", c)
	}

	u, err := parseConf(unpaired)
	if err != nil {
		t.Fatalf("unpaired config rejected: %v", err)
	}
	if u.HasPeer {
		t.Fatal("unpaired config reported a peer")
	}
}

// Everything here must fail closed: an accepted case would widen or divert the tunnel.
func TestParseRejects(t *testing.T) {
	cases := map[string]string{
		"no interface":       "[Peer]\nPublicKey = " + peerKey + "\nAllowedIPs = 10.77.77.2/32\n",
		"two interfaces":     unpaired + "\n[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.3/32\nListenPort = 51821\n",
		"two peers":          paired + "\n[Peer]\nPublicKey = " + peerKey + "\nAllowedIPs = 10.77.77.3/32\n",
		"missing privatekey": "[Interface]\nAddress = 10.77.77.1/32\nListenPort = 51820\n",
		"missing address":    "[Interface]\nPrivateKey = " + privKey + "\nListenPort = 51820\n",
		"missing port":       "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\n",
		"bad key":            "[Interface]\nPrivateKey = nope\nAddress = 10.77.77.1/32\nListenPort = 51820\n",
		"unpadded key":       "[Interface]\nPrivateKey = AwoRGB8mLTQ7QklQV15lbHN6gYiPlp2kq7K5wMfO1dwx\nAddress = 10.77.77.1/32\nListenPort = 51820\n",
		"port zero":          "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 0\n",
		"port too big":       "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 70000\n",
		"address /24":        "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/24\nListenPort = 51820\n",
		"address off subnet": "[Interface]\nPrivateKey = " + privKey + "\nAddress = 192.168.1.5/32\nListenPort = 51820\n",
		"network address":    "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.0/32\nListenPort = 51820\n",
		"duplicate key":      "[Interface]\nPrivateKey = " + privKey + "\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n",
		"unknown section":    unpaired + "\n[Nonsense]\nFoo = 1\n",
		"key before section": "PrivateKey = " + privKey + "\n" + unpaired,
		"not key = value":    unpaired + "garbage\n",

		// The keys that could widen or divert this tunnel.
		"DNS":                 unpaired + "DNS = 1.1.1.1\n",
		"MTU":                 unpaired + "MTU = 1280\n",
		"Table":               unpaired + "Table = off\n",
		"PreUp":               unpaired + "PreUp = /bin/sh -c evil\n",
		"PostUp":              unpaired + "PostUp = /bin/sh -c evil\n",
		"Endpoint":            paired + "Endpoint = 1.2.3.4:51820\n",
		"default route":       "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n\n[Peer]\nPublicKey = " + peerKey + "\nAllowedIPs = 0.0.0.0/0\n",
		"wide allowed ips":    "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n\n[Peer]\nPublicKey = " + peerKey + "\nAllowedIPs = 10.77.77.0/24\n",
		"allowed ips list":    "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n\n[Peer]\nPublicKey = " + peerKey + "\nAllowedIPs = 10.77.77.2/32, 0.0.0.0/0\n",
		"allowed ips foreign": "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n\n[Peer]\nPublicKey = " + peerKey + "\nAllowedIPs = 8.8.8.8/32\n",
		"peer is us":          "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n\n[Peer]\nPublicKey = " + peerKey + "\nAllowedIPs = 10.77.77.1/32\n",
		"peer no key":         "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n\n[Peer]\nAllowedIPs = 10.77.77.2/32\n",
		"peer no allowed ips": "[Interface]\nPrivateKey = " + privKey + "\nAddress = 10.77.77.1/32\nListenPort = 51820\n\n[Peer]\nPublicKey = " + peerKey + "\n",
	}
	for name, text := range cases {
		if _, err := parseConf(text); err == nil {
			t.Errorf("%s: accepted, want rejection", name)
		}
	}
}

func TestUAPI(t *testing.T) {
	c, err := parseConf(paired)
	if err != nil {
		t.Fatal(err)
	}
	got, err := c.uapi()
	if err != nil {
		t.Fatal(err)
	}
	want := "private_key=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dc\n" +
		"listen_port=51820\n" +
		"replace_peers=true\n" +
		"public_key=000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f\n" +
		"replace_allowed_ips=true\n" +
		"allowed_ip=10.77.77.2/32\n\n"
	if got != want {
		t.Errorf("paired UAPI mismatch:\ngot  %q\nwant %q", got, want)
	}

	u, err := parseConf(unpaired)
	if err != nil {
		t.Fatal(err)
	}
	got, err = u.uapi()
	if err != nil {
		t.Fatal(err)
	}
	want = "private_key=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dc\n" +
		"listen_port=51820\n" +
		"replace_peers=true\n\n"
	if got != want {
		t.Errorf("unpaired UAPI mismatch:\ngot  %q\nwant %q", got, want)
	}
}

func TestStatusFields(t *testing.T) {
	reply := "private_key=030a11181f262d343b424950575e656c737a81888f969da4abb2b9c0c7ced5dc\n" +
		"listen_port=51820\n" +
		"public_key=000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f\n" +
		"endpoint=203.0.113.7:51820\n" +
		"allowed_ip=10.77.77.2/32\n" +
		"last_handshake_time_sec=1700000000\n" +
		"last_handshake_time_nsec=12\n" +
		"tx_bytes=4096\n" +
		"rx_bytes=2048\n" +
		"persistent_keepalive_interval=25\n" +
		"errno=0\n"
	got := statusFields(reply)
	want := []string{
		"public_key=" + mustPub(t, privKey),
		"listen_port=51820",
		"peer_public_key=" + peerKey,
		"endpoint=203.0.113.7:51820",
		"allowed_ips=10.77.77.2/32",
		"last_handshake_unix=1700000000",
		"rx_bytes=2048",
		"tx_bytes=4096",
		"persistent_keepalive=25",
	}
	if len(got) != len(want)+1 || got[0][:len("interface=")] != "interface=" {
		t.Fatalf("unexpected field set: %q", got)
	}
	for i, w := range want {
		if got[i+1] != w {
			t.Errorf("field %d: got %q want %q", i+1, got[i+1], w)
		}
	}

	// An empty reply must still render every key, with safe zero values.
	empty := statusFields("errno=0\n")
	for _, want := range []string{"peer_public_key=", "endpoint=", "allowed_ips=", "last_handshake_unix=0", "rx_bytes=0", "tx_bytes=0", "persistent_keepalive=0"} {
		found := false
		for _, line := range empty {
			if line == want {
				found = true
			}
		}
		if !found {
			t.Errorf("missing %q in %q", want, empty)
		}
	}
}

func mustPub(t *testing.T, priv string) string {
	t.Helper()
	p, err := publicKey(priv)
	if err != nil {
		t.Fatal(err)
	}
	return p
}
