#!/usr/bin/env bash
# scshr macOS tunnel + Screen Sharing isolation.
#
#   sudo ./tools/scshr-macos-tunnel.sh init --endpoint my-mac.example.net [--listen-port 51820]
#   sudo ./tools/scshr-macos-tunnel.sh pair 'SCCL1:<windows-code>'
#   sudo ./tools/scshr-macos-tunnel.sh up | down | status
#   sudo ./tools/scshr-macos-tunnel.sh uninstall [--reset-identity]
#
# This is NOT a VPN. It creates one WireGuard peering between this Mac (10.77.77.1) and one paired
# Windows machine (10.77.77.2) and then restricts Screen Sharing so it is reachable only across
# that peering. Nothing here enables forwarding, NAT or routing: the Mac is never an exit node.
#
# Everything is idempotent; nothing persistent is mutated before every prerequisite and every
# generated file has been validated, and a failed firewall activation is rolled back.
set -euo pipefail

# ── constants ─────────────────────────────────────────────────────────────────────────────────
TUNNEL_NAME="scshr"
TUNNEL_SUBNET_PREFIX="10.77.77."
DEFAULT_MAC_IP="10.77.77.1"
DEFAULT_WIN_IP="10.77.77.2"
DEFAULT_LISTEN_PORT="51820"

STATE_DIR="/usr/local/etc/scshr"
CONF="${STATE_DIR}/${TUNNEL_NAME}.conf"
PRIV_KEY="${STATE_DIR}/private.key"
PUB_KEY="${STATE_DIR}/public.key"
SETTINGS="${STATE_DIR}/settings"
PF_BACKUP_DIR="${STATE_DIR}/pf-backups"
PF_ANCHOR="/etc/pf.anchors/${TUNNEL_NAME}"
PF_CONF="/etc/pf.conf"
PF_ANCHOR_LINE="anchor \"${TUNNEL_NAME}\""
PF_LOAD_LINE="load anchor \"${TUNNEL_NAME}\" from \"${PF_ANCHOR}\""
LAUNCHD_PLIST="/Library/LaunchDaemons/net.scshr.tunnel.plist"
INSTALLED_SCRIPT="/usr/local/libexec/scshr-macos-tunnel.sh"

# Mac-side ports scshr actually uses (src/session/session.h): TCP 5900 control/RFB record layer,
# UDP 5900 audio + RTCP, UDP 5901 video. Screen Sharing itself listens on TCP 5900.
SCSHR_TCP_PORTS="5900"
SCSHR_UDP_PORTS="5900 5901"

die() { printf 'scshr: %s\n' "$*" >&2; exit 1; }
info() { printf 'scshr: %s\n' "$*"; }

# ── small helpers ─────────────────────────────────────────────────────────────────────────────
b64e() { base64 | tr -d '\n'; }
b64d() { if base64 --decode </dev/null >/dev/null 2>&1; then base64 --decode; else base64 -D; fi; }
b64url_encode() { b64e | tr '+/' '-_' | tr -d '='; }
b64url_decode() {
    local s; s="$(cat)"
    case $(( ${#s} % 4 )) in 2) s="${s}==" ;; 3) s="${s}=" ;; 1) return 1 ;; esac
    printf '%s' "$s" | tr -- '-_' '+/' | b64d
}

need_root() { [ "$(id -u)" = "0" ] || die "this command must run as root (use sudo)"; }

# Locates a supported WireGuard implementation. Homebrew installs under /usr/local or /opt/homebrew.
find_wireguard() {
    local extra="/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:/opt/homebrew/sbin"
    PATH="${extra}:${PATH}"
    export PATH
    command -v wg >/dev/null 2>&1 || die "wg not found — install WireGuard tools (brew install wireguard-tools)"
    command -v wg-quick >/dev/null 2>&1 || die "wg-quick not found — install WireGuard tools (brew install wireguard-tools)"
}

is_wg_key() { printf '%s' "$1" | grep -Eq '^[A-Za-z0-9+/]{42}[A-Za-z0-9+/=]=$'; }

is_tunnel_ip() {
    case "$1" in
        "${TUNNEL_SUBNET_PREFIX}"*) ;;
        *) return 1 ;;
    esac
    local last="${1#"${TUNNEL_SUBNET_PREFIX}"}"
    printf '%s' "$last" | grep -Eq '^[0-9]{1,3}$' || return 1
    [ "$last" -ge 1 ] 2>/dev/null && [ "$last" -le 254 ]
}

is_port() { printf '%s' "$1" | grep -Eq '^[1-9][0-9]{0,4}$' && [ "$1" -le 65535 ]; }

is_endpoint_host() {
    local h="$1"
    [ -n "$h" ] || return 1
    [ "${#h}" -le 253 ] || return 1
    if printf '%s' "$h" | grep -Eq '^[0-9]+(\.[0-9]+){3}$'; then
        local a b c d; IFS=. read -r a b c d <<EOF
$h
EOF
        for o in "$a" "$b" "$c" "$d"; do [ "$o" -le 255 ] 2>/dev/null || return 1; done
        [ "$a" != "0" ] && [ "$a" != "127" ] && [ "$a" -lt 224 ] || return 1
        return 0
    fi
    printf '%s' "$h" | grep -Eq '^[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?(\.[A-Za-z0-9]([A-Za-z0-9-]*[A-Za-z0-9])?)*$'
}

# ── generators (pure; used by the tests via the render-* subcommands) ─────────────────────────
render_conf() {   # <private-key> <mac-ip> <listen-port> [<peer-public-key> <peer-ip>]
    printf '%s\n' "# Generated by scshr-macos-tunnel.sh - do not edit by hand."
    printf '%s\n' "# scshr application tunnel: one macOS peer <-> one Windows peer, no forwarding, no NAT."
    printf '%s\n' "[Interface]"
    printf 'PrivateKey = %s\n' "$1"
    printf 'Address = %s/32\n' "$2"
    printf 'ListenPort = %s\n' "$3"
    if [ -n "${4:-}" ]; then
        printf '\n%s\n' "[Peer]"
        printf 'PublicKey = %s\n' "$4"
        # No Endpoint: the Windows peer roams and is learned from its own handshake.
        printf 'AllowedIPs = %s/32\n' "$5"
    fi
}

render_pf() {   # <mac-ip> <win-ip> <listen-port>
    local mac="$1" win="$2" port="$3"
    printf '%s\n' "# Generated by scshr-macos-tunnel.sh - do not edit by hand."
    printf '%s\n' "# scshr Screen Sharing isolation. First match wins (quick), so the passes come first."
    printf '%s\n' "# Address-based on purpose: the utun interface number is not stable across boots."
    printf 'pass in quick proto udp from any to any port %s keep state\n' "$port"
    printf 'pass in quick proto tcp from 127.0.0.1 to 127.0.0.1 port { %s } keep state\n' "$SCSHR_TCP_PORTS"
    printf 'pass in quick proto udp from 127.0.0.1 to 127.0.0.1 port { %s } keep state\n' "$SCSHR_UDP_PORTS"
    printf 'pass in quick proto tcp from %s to %s port { %s } keep state\n' "$win" "$mac" "$SCSHR_TCP_PORTS"
    printf 'pass in quick proto udp from %s to %s port { %s } keep state\n' "$win" "$mac" "$SCSHR_UDP_PORTS"
    printf 'block drop in quick proto tcp from any to any port { %s }\n' "$SCSHR_TCP_PORTS"
    printf 'block drop in quick proto udp from any to any port { %s }\n' "$SCSHR_UDP_PORTS"
}

render_server_code() {   # <public-key> <endpoint> <listen-port> <mac-ip> <win-ip>
    is_wg_key "$1" || die "invalid WireGuard public key"
    is_endpoint_host "$2" || die "invalid endpoint host: $2"
    is_port "$3" || die "invalid listen port: $3"
    is_tunnel_ip "$4" || die "invalid mac tunnel IP: $4"
    is_tunnel_ip "$5" || die "invalid windows tunnel IP: $5"
    [ "$4" != "$5" ] || die "tunnel IPs must differ"
    printf 'SCST1:%s' "$(printf 'k=%s\ne=%s\np=%s\ns=%s\nc=%s' "$1" "$2" "$3" "$4" "$5" | b64url_encode)"
    printf '\n'
}

render_client_code() {   # <public-key> <win-ip>   (only used to cross-check the Windows encoder)
    is_wg_key "$1" || die "invalid WireGuard public key"
    is_tunnel_ip "$2" || die "invalid windows tunnel IP: $2"
    printf 'SCCL1:%s' "$(printf 'k=%s\nc=%s' "$1" "$2" | b64url_encode)"
    printf '\n'
}

# Strictly decodes SCCL1 into WIN_PUB / WIN_IP.
decode_client_code() {
    local code="$1" body
    case "$code" in
        SCCL1:*) ;;
        SCCL[0-9]:*|SCCL*:*) die "unsupported pairing descriptor version" ;;
        *) die "not an SCCL1 pairing descriptor" ;;
    esac
    local payload="${code#SCCL1:}"
    [ -n "$payload" ] || die "empty pairing descriptor"
    [ "${#payload}" -le 1024 ] && printf '%s' "$payload" | grep -Eq '^[A-Za-z0-9_-]+$' || die "invalid base64url payload"
    body="$(printf '%s' "$payload" | b64url_decode)" || die "invalid base64url payload"
    [ "$(printf '%s' "$body" | wc -l | tr -d ' ')" = "1" ] || die "malformed pairing descriptor"
    WIN_PUB="$(printf '%s' "$body" | sed -n '1s/^k=//p')"
    WIN_IP="$(printf '%s' "$body" | sed -n '2s/^c=//p')"
    [ -n "$WIN_PUB" ] || die "malformed pairing descriptor: missing key field"
    [ -n "$WIN_IP" ] || die "malformed pairing descriptor: missing address field"
    is_wg_key "$WIN_PUB" || die "invalid WireGuard public key in pairing descriptor"
    is_tunnel_ip "$WIN_IP" || die "windows tunnel IP outside ${TUNNEL_SUBNET_PREFIX}0/24: $WIN_IP"
    [ "$WIN_IP" != "$(setting mac_ip "$DEFAULT_MAC_IP")" ] || die "the paired peer claims this Mac's tunnel address"
}

# ── settings ──────────────────────────────────────────────────────────────────────────────────
setting() {   # <key> [<default>]
    if [ -f "$SETTINGS" ]; then
        local v
        v="$(sed -n "s/^$1=//p" "$SETTINGS" | tail -n1)"
        [ -n "$v" ] && { printf '%s' "$v"; return 0; }
    fi
    printf '%s' "${2:-}"
}

save_settings() {   # endpoint port mac_ip win_ip peer_pub
    umask 077
    mkdir -p "$STATE_DIR"
    {
        printf 'endpoint=%s\n' "$1"
        printf 'listen_port=%s\n' "$2"
        printf 'mac_ip=%s\n' "$3"
        printf 'win_ip=%s\n' "$4"
        printf 'peer_public_key=%s\n' "$5"
    } >"${SETTINGS}.tmp"
    chmod 600 "${SETTINGS}.tmp"
    mv -f "${SETTINGS}.tmp" "$SETTINGS"
}

# ── identity ──────────────────────────────────────────────────────────────────────────────────
ensure_identity() {
    umask 077
    mkdir -p "$STATE_DIR"
    chown root:wheel "$STATE_DIR"
    chmod 700 "$STATE_DIR"
    if [ -s "$PRIV_KEY" ] && [ -s "$PUB_KEY" ]; then
        is_wg_key "$(cat "$PRIV_KEY")" || die "stored private key is corrupt (uninstall --reset-identity to start over)"
        info "identity: existing key preserved"
        return
    fi
    [ ! -e "$PRIV_KEY" ] && [ ! -e "$PUB_KEY" ] || die "identity is half-written — run 'uninstall --reset-identity' first"
    wg genkey >"${PRIV_KEY}.tmp"
    chmod 600 "${PRIV_KEY}.tmp"
    mv -f "${PRIV_KEY}.tmp" "$PRIV_KEY"
    wg pubkey <"$PRIV_KEY" >"$PUB_KEY"
    chmod 644 "$PUB_KEY"
    chown root:wheel "$PRIV_KEY" "$PUB_KEY"
    info "identity: new keypair generated (private key never leaves this Mac)"
}

# ── configuration ─────────────────────────────────────────────────────────────────────────────
write_conf() {   # rewrites $CONF from the stored identity + settings; only when the bytes differ
    local peer_pub peer_ip staged
    peer_pub="$(setting peer_public_key)"
    peer_ip="$(setting win_ip "$DEFAULT_WIN_IP")"
    staged="$(mktemp)"
    if [ -n "$peer_pub" ]; then
        render_conf "$(cat "$PRIV_KEY")" "$(setting mac_ip "$DEFAULT_MAC_IP")" "$(setting listen_port "$DEFAULT_LISTEN_PORT")" "$peer_pub" "$peer_ip" >"$staged"
    else
        render_conf "$(cat "$PRIV_KEY")" "$(setting mac_ip "$DEFAULT_MAC_IP")" "$(setting listen_port "$DEFAULT_LISTEN_PORT")" >"$staged"
    fi
    # Validate before anything persistent changes: wg parses the [Interface]/[Peer] stanzas itself.
    if ! wg-quick strip "$staged" >/dev/null 2>&1; then
        rm -f "$staged"
        die "generated WireGuard configuration failed validation"
    fi
    if [ -f "$CONF" ] && cmp -s "$staged" "$CONF"; then
        rm -f "$staged"
        return 1
    fi
    chmod 600 "$staged"
    mv -f "$staged" "$CONF"
    chown root:wheel "$CONF"
    return 0
}

# ── firewall (mandatory) ──────────────────────────────────────────────────────────────────────
install_pf() {
    local mac win port staged anchor_tmp backup
    mac="$(setting mac_ip "$DEFAULT_MAC_IP")"
    win="$(setting win_ip "$DEFAULT_WIN_IP")"
    port="$(setting listen_port "$DEFAULT_LISTEN_PORT")"

    anchor_tmp="$(mktemp)"
    render_pf "$mac" "$win" "$port" >"$anchor_tmp"
    mkdir -p /etc/pf.anchors
    install -m 644 -o root -g wheel "$anchor_tmp" "$PF_ANCHOR"
    rm -f "$anchor_tmp"
    pfctl -n -f "$PF_ANCHOR" >/dev/null 2>&1 || die "generated PF anchor failed syntax validation — no firewall change was made"

    staged="$(mktemp)"
    cp "$PF_CONF" "$staged"
    if ! grep -Fq "$PF_LOAD_LINE" "$staged"; then
        # Smallest possible edit: two lines appended to the filter section.
        {
            printf '\n# scshr application tunnel isolation (added by scshr-macos-tunnel.sh)\n'
            printf '%s\n' "$PF_ANCHOR_LINE"
            printf '%s\n' "$PF_LOAD_LINE"
        } >>"$staged"
    fi
    if ! pfctl -n -f "$staged" >/dev/null 2>&1; then
        rm -f "$staged"
        die "PF configuration failed syntax validation — /etc/pf.conf was left untouched"
    fi

    mkdir -p "$PF_BACKUP_DIR"
    chmod 700 "$PF_BACKUP_DIR"
    backup="${PF_BACKUP_DIR}/pf.conf.$(date +%Y%m%d%H%M%S)"
    cp "$PF_CONF" "$backup"
    install -m 644 -o root -g wheel "$staged" "$PF_CONF"
    rm -f "$staged"

    if ! pfctl -E -f "$PF_CONF" >/dev/null 2>&1; then
        install -m 644 -o root -g wheel "$backup" "$PF_CONF"
        pfctl -f "$PF_CONF" >/dev/null 2>&1 || true
        die "activating PF failed — /etc/pf.conf was restored from ${backup}; Screen Sharing isolation is NOT installed"
    fi
    info "firewall: Screen Sharing (tcp ${SCSHR_TCP_PORTS}, udp ${SCSHR_UDP_PORTS}) reachable only from ${win}; udp/${port} open for WireGuard"
}

remove_pf() {
    if [ -f "$PF_CONF" ] && grep -Fq "$PF_LOAD_LINE" "$PF_CONF"; then
        local staged
        staged="$(mktemp)"
        grep -Fv "$PF_ANCHOR_LINE" "$PF_CONF" | grep -Fv "$PF_LOAD_LINE" |
            grep -Fv '# scshr application tunnel isolation (added by scshr-macos-tunnel.sh)' >"$staged"
        if pfctl -n -f "$staged" >/dev/null 2>&1; then
            install -m 644 -o root -g wheel "$staged" "$PF_CONF"
            pfctl -f "$PF_CONF" >/dev/null 2>&1 || true
            info "removed the scshr anchor from ${PF_CONF}"
        else
            info "WARNING: could not remove the scshr anchor cleanly; ${PF_CONF} left as is"
        fi
        rm -f "$staged"
    fi
    rm -f "$PF_ANCHOR"
    # PF itself is left enabled/disabled exactly as it was; other anchors are never touched.
}

# ── persistence ───────────────────────────────────────────────────────────────────────────────
install_launchd() {
    mkdir -p "$(dirname "$INSTALLED_SCRIPT")"
    install -m 755 -o root -g wheel "$0" "$INSTALLED_SCRIPT"
    cat >"${LAUNCHD_PLIST}.tmp" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>net.scshr.tunnel</string>
    <key>ProgramArguments</key>
    <array>
        <string>${INSTALLED_SCRIPT}</string>
        <string>up</string>
    </array>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><false/>
    <key>StandardErrorPath</key><string>/var/log/scshr-tunnel.log</string>
</dict>
</plist>
PLIST
    install -m 644 -o root -g wheel "${LAUNCHD_PLIST}.tmp" "$LAUNCHD_PLIST"
    rm -f "${LAUNCHD_PLIST}.tmp"
    launchctl unload "$LAUNCHD_PLIST" >/dev/null 2>&1 || true
    launchctl load -w "$LAUNCHD_PLIST" >/dev/null 2>&1 || info "WARNING: launchctl load failed; the tunnel will not come back automatically after a reboot"
}

# ── lifecycle ─────────────────────────────────────────────────────────────────────────────────
tunnel_is_up() { wg show "$TUNNEL_NAME" >/dev/null 2>&1; }

cmd_up() {
    need_root
    find_wireguard
    [ -f "$CONF" ] || die "not initialised — run 'init' first"
    pfctl -E -f "$PF_CONF" >/dev/null 2>&1 || die "could not activate PF — refusing to start the tunnel with Screen Sharing exposed"
    tunnel_is_up || wg-quick up "$CONF"
    info "tunnel up: $(setting mac_ip "$DEFAULT_MAC_IP")/32 listening on udp/$(setting listen_port "$DEFAULT_LISTEN_PORT")"
}

cmd_down() {
    need_root
    find_wireguard
    if tunnel_is_up; then wg-quick down "$CONF"; fi
    # PF rules stay in place: taking the tunnel down must not re-expose Screen Sharing.
    info "tunnel down (Screen Sharing isolation remains active)"
}

cmd_init() {
    local endpoint="" port="$DEFAULT_LISTEN_PORT" mac_ip="$DEFAULT_MAC_IP" win_ip="$DEFAULT_WIN_IP"
    while [ $# -gt 0 ]; do
        case "$1" in
            --endpoint) endpoint="${2:-}"; shift 2 ;;
            --listen-port) port="${2:-}"; shift 2 ;;
            --mac-ip) mac_ip="${2:-}"; shift 2 ;;
            --win-ip) win_ip="${2:-}"; shift 2 ;;
            *) die "unknown argument: $1" ;;
        esac
    done
    need_root
    find_wireguard
    command -v pfctl >/dev/null 2>&1 || die "pfctl not found — this script requires macOS packet filter"
    [ -f "$PF_CONF" ] || die "${PF_CONF} not found — refusing to create one from scratch"
    [ -n "$endpoint" ] || die "--endpoint is required: the public hostname or IP at which this Mac's WireGuard port is reachable"
    is_endpoint_host "$endpoint" || die "invalid --endpoint: $endpoint"
    is_port "$port" || die "invalid --listen-port: $port"
    is_tunnel_ip "$mac_ip" || die "invalid --mac-ip (must be inside ${TUNNEL_SUBNET_PREFIX}0/24): $mac_ip"
    is_tunnel_ip "$win_ip" || die "invalid --win-ip (must be inside ${TUNNEL_SUBNET_PREFIX}0/24): $win_ip"
    [ "$mac_ip" != "$win_ip" ] || die "--mac-ip and --win-ip must differ"

    ensure_identity
    save_settings "$endpoint" "$port" "$mac_ip" "$win_ip" "$(setting peer_public_key)"
    if write_conf; then info "configuration written to ${CONF}"; else info "configuration already current"; fi
    install_pf
    install_launchd
    if tunnel_is_up; then wg-quick down "$CONF" >/dev/null 2>&1 || true; fi
    wg-quick up "$CONF"

    if [ "$(sysctl -n net.inet.ip.forwarding 2>/dev/null || echo 0)" != "0" ]; then
        info "NOTE: IP forwarding is enabled on this Mac by something else — scshr did not enable it and does not need it"
    fi

    printf '\n'
    info "macOS tunnel ready. Give this pairing code to Windows:"
    printf '\n    %s\n\n' "$(render_server_code "$(cat "$PUB_KEY")" "$endpoint" "$port" "$mac_ip" "$win_ip")"
    printf 'Next:\n'
    printf '  1. On Windows:  .\\scshr.exe init      (paste the code above)\n'
    printf '  2. Back here :  sudo %s pair '"'"'SCCL1:<code Windows printed>'"'"'\n' "$0"
    printf '\nIf this Mac is behind NAT, forward udp/%s to it; nothing else needs to be reachable.\n' "$port"
}

cmd_pair() {
    local code="${1:-}"
    [ -n "$code" ] || die "usage: pair 'SCCL1:<windows-code>'"
    need_root
    find_wireguard
    [ -s "$PRIV_KEY" ] || die "not initialised — run 'init' first"
    decode_client_code "$code"
    [ "$WIN_IP" = "$(setting win_ip "$DEFAULT_WIN_IP")" ] ||
        die "the Windows peer claims ${WIN_IP} but this Mac was initialised for $(setting win_ip "$DEFAULT_WIN_IP")"
    save_settings "$(setting endpoint)" "$(setting listen_port "$DEFAULT_LISTEN_PORT")" \
                  "$(setting mac_ip "$DEFAULT_MAC_IP")" "$WIN_IP" "$WIN_PUB"
    if write_conf; then
        if tunnel_is_up; then wg-quick down "$CONF"; fi
        wg-quick up "$CONF"
        info "paired with Windows peer $(printf '%s' "$WIN_PUB" | cut -c1-8)… at ${WIN_IP}/32"
    else
        info "already paired with this peer"
    fi
    install_pf
}

cmd_status() {
    need_root
    find_wireguard
    printf 'scshr macOS tunnel\n'
    printf '  configuration   : %s\n' "$([ -f "$CONF" ] && echo present || echo missing)"
    printf '  local address   : %s/32\n' "$(setting mac_ip "$DEFAULT_MAC_IP")"
    printf '  peer address    : %s/32\n' "$(setting win_ip "$DEFAULT_WIN_IP")"
    printf '  public endpoint : %s:%s\n' "$(setting endpoint '(unset)')" "$(setting listen_port "$DEFAULT_LISTEN_PORT")"
    printf '  public key      : %s\n' "$([ -f "$PUB_KEY" ] && cat "$PUB_KEY" || echo '(none)')"
    if tunnel_is_up; then
        printf '  state           : up on %s\n' "$(wg show "$TUNNEL_NAME" 2>/dev/null | sed -n '1s/^interface: //p')"
        wg show "$TUNNEL_NAME" | sed 's/^/    /'
    else
        printf '  state           : down\n'
    fi
    printf '  ip forwarding   : %s (scshr never enables it)\n' "$(sysctl -n net.inet.ip.forwarding 2>/dev/null || echo unknown)"
    printf '  pf              : %s\n' "$(pfctl -s info 2>/dev/null | sed -n '1s/^Status: //p' || echo unknown)"
    printf '  isolation rules :\n'
    pfctl -a "$TUNNEL_NAME" -s rules 2>/dev/null | sed 's/^/    /' || printf '    (anchor not loaded)\n'
    printf '  launchd         : %s\n' "$([ -f "$LAUNCHD_PLIST" ] && echo installed || echo 'not installed')"
    # Private key material is never printed.
}

cmd_uninstall() {
    local reset=0
    while [ $# -gt 0 ]; do
        case "$1" in
            --reset-identity) reset=1; shift ;;
            *) die "unknown argument: $1" ;;
        esac
    done
    need_root
    find_wireguard
    if tunnel_is_up; then wg-quick down "$CONF" >/dev/null 2>&1 || true; fi
    if [ -f "$LAUNCHD_PLIST" ]; then
        launchctl unload "$LAUNCHD_PLIST" >/dev/null 2>&1 || true
        rm -f "$LAUNCHD_PLIST"
        info "removed ${LAUNCHD_PLIST}"
    fi
    rm -f "$INSTALLED_SCRIPT"
    remove_pf
    rm -f "$CONF" "$SETTINGS"
    if [ "$reset" = "1" ]; then
        rm -f "$PRIV_KEY" "$PUB_KEY"
        info "identity keys removed"
    else
        info "identity keys preserved (pass --reset-identity to discard them)"
    fi
    rmdir "$STATE_DIR" 2>/dev/null || true
    info "removed scshr-owned state only; other WireGuard tunnels, PF anchors and software were not touched"
}

usage() {
    cat <<USAGE
scshr macOS tunnel

  sudo $0 init --endpoint HOST [--listen-port ${DEFAULT_LISTEN_PORT}] [--mac-ip ${DEFAULT_MAC_IP}] [--win-ip ${DEFAULT_WIN_IP}]
  sudo $0 pair 'SCCL1:<windows-code>'
  sudo $0 up | down | status
  sudo $0 uninstall [--reset-identity]

Test helpers (no root, no side effects):
  $0 render-conf <private-key> <mac-ip> <port> [<peer-public-key> <peer-ip>]
  $0 render-pf <mac-ip> <win-ip> <listen-port>
  $0 render-server-code <public-key> <endpoint> <port> <mac-ip> <win-ip>
  $0 render-client-code <public-key> <win-ip>
  $0 decode-client-code <SCCL1:...>
USAGE
}

case "${1:-}" in
    init) shift; cmd_init "$@" ;;
    pair) shift; cmd_pair "$@" ;;
    up) shift; cmd_up "$@" ;;
    down) shift; cmd_down "$@" ;;
    status) shift; cmd_status "$@" ;;
    uninstall) shift; cmd_uninstall "$@" ;;
    render-conf) shift; render_conf "$@" ;;
    render-pf) shift; render_pf "$@" ;;
    render-server-code) shift; render_server_code "$@" ;;
    render-client-code) shift; render_client_code "$@" ;;
    decode-client-code) shift; decode_client_code "${1:-}"; printf '%s %s\n' "$WIN_PUB" "$WIN_IP" ;;
    -h|--help|help|"") usage ;;
    *) usage; exit 2 ;;
esac
